# -*- coding: utf-8 -*-
"""project3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176JP2Uf5sa2MrcxLoJFc4akG5_7NixJn
"""



import re
import gradio as gr
from transformers import MarianMTModel, MarianTokenizer

# Load model
model_name = "Helsinki-NLP/opus-mt-en-hi"

tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)


# Create Translator Class
class EnglishToHindiTranslator:

    def __init__(self, model, tokenizer):
        self.model = model
        self.tokenizer = tokenizer

    # clean text
    def clean(self, text):
        text = re.sub(r"\n+", " ", text)
        text = re.sub(r" +", " ", text)
        return text.strip()

    # main translation function
    def __call__(self, text):

        if not text:
            return "Please enter some English text."

        text = self.clean(text)

        # Tokenize input
        inputs = self.tokenizer(
            text,
            return_tensors="pt",
            truncation=True
        )

        # Generate translation
        translated_tokens = self.model.generate(
            inputs["input_ids"],
            attention_mask=inputs["attention_mask"]
        )

        # Decode tokens to Hindi text
        output = self.tokenizer.decode(
            translated_tokens[0],
            skip_special_tokens=True
        )

        return output


# Create object
translator = EnglishToHindiTranslator(model, tokenizer)

def clean(text):
    text = re.sub(r'\n+', ' ', text)
    text = re.sub(r' +', ' ', text)
    return text.strip()

# Now how my input should be
def translate_text(text):
    return translator(text)

app = gr.Interface(
    fn=translate_text,
    inputs=gr.Textbox(
        lines=10,
        placeholder="Type English text here",
        label="English Input"
    ),
    outputs=gr.Textbox(
        lines=8,
        label="Hindi Translation"
    ),
    title="English → Hindi Translator"
)

app.launch(share=True)